import { createApi } from '@reduxjs/toolkit/query/react';
import { axiosClient } from '../../../api/axiosClient';

// A custom baseQuery function wrapping our pre-configured axios client
const axiosBaseQuery =
    ({ baseUrl } = { baseUrl: '' }) =>
    async ({ url, method, data, params, headers }) => {
        try {
            const result = await axiosClient({
                url: baseUrl + url,
                method,
                data,
                params,
                headers,
            });
            return { data: result.data };
        } catch (axiosError) {
            const err = axiosError;
            return {
                error: {
                    status: err.response?.status,
                    data: err.response?.data || err.message,
                },
            };
        }
    };

export const productApi = createApi({
    reducerPath: 'productApi',
    baseQuery: axiosBaseQuery(),
    tagTypes: ['Product', 'Repair', 'Spec'], // Used for automatic cache invalidation
    endpoints: (builder) => ({
        // Queries
        getProducts: builder.query({
            query: () => ({ url: '/asset/products', method: 'GET' }),
            providesTags: (result) =>
                result
                    ? [
                          ...result.map(({ id }) => ({ type: 'Product', id })),
                          { type: 'Product', id: 'LIST' },
                      ]
                    : [{ type: 'Product', id: 'LIST' }],
        }),
        getProductById: builder.query({
            query: (id) => ({ url: `/asset/products/${id}`, method: 'GET' }),
            providesTags: (result, error, id) => [{ type: 'Product', id }],
        }),
        getAssetUsers: builder.query({
            query: () => ({ url: '/asset/users', method: 'GET' }),
        }),

        // Mutations
        addProduct: builder.mutation({
            query: (newProduct) => ({
                url: '/asset/products',
                method: 'POST',
                data: newProduct,
            }),
            // Invalidates the list so getProducts runs again automatically
            invalidatesTags: [{ type: 'Product', id: 'LIST' }],
        }),
        updateProduct: builder.mutation({
            query: ({ id, ...patch }) => ({
                url: `/asset/products/${id}`,
                method: 'PUT',
                data: patch,
            }),
            // Invalidates both the specific product and the list
            invalidatesTags: (result, error, { id }) => [
                { type: 'Product', id },
                { type: 'Product', id: 'LIST' },
            ],
        }),
        deleteProduct: builder.mutation({
            query: (id) => ({
                url: `/asset/products/${id}`,
                method: 'DELETE',
            }),
            invalidatesTags: (result, error, id) => [
                { type: 'Product', id },
                { type: 'Product', id: 'LIST' },
            ],
        }),

        // Sub-resources
        addRepair: builder.mutation({
            query: ({ productId, repairData }) => ({
                url: `/asset/repairs/product/${productId}`,
                method: 'POST',
                data: repairData,
            }),
            // Invalidate the specific product so its repair summary re-fetches
            invalidatesTags: (result, error, { productId }) => [{ type: 'Product', id: productId }],
        }),
    }),
});

// Export hooks for usage in functional components, auto-generated by RTK Query
export const {
    useGetProductsQuery,
    useGetProductByIdQuery,
    useGetAssetUsersQuery,
    useAddProductMutation,
    useUpdateProductMutation,
    useDeleteProductMutation,
    useAddRepairMutation
} = productApi;
